# Generated by Django 6.0.6 on 2026-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
    ]
