# Generated by Django 6.0.6 on 2026-06-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='imagem',
            field=models.ImageField(upload_to='personagens/'),
        ),
    ]
